

-- Tabelle: T_DEVICE
-- Enthält alle registrierten Geräte mit Koordinaten.
CREATE TABLE ITP.T_DEVICE
( 
	PK_DEVICEID INT PRIMARY KEY NOT NULL, 
	IDENTIFIER VARCHAR(17) NOT NULL, 
	ACTIVITY DATETIME NOT NULL, 
	LATITUDE DOUBLE NOT NULL, 
	LONGITUDE DOUBLE NOT NULL 
);
ALTER TABLE ITP.T_DEVICE ADD CONSTRAINT IDENTIFIER_UNIQUE UNIQUE(IDENTIFIER);
CREATE SEQUENCE ITP.S_DEVICE;

INSERT INTO ITP.T_DEVICE (PK_DEVICEID, IDENTIFIER, ACTIVITY, LATITUDE, LONGITUDE) VALUES (NEXTVAL('ITP.S_DEVICE'), '00-B0-D0-86-BB-F7', CURRENT_TIMESTAMP(), 49.456409, 11.078682);
INSERT INTO ITP.T_DEVICE (PK_DEVICEID, IDENTIFIER, ACTIVITY, LATITUDE, LONGITUDE) VALUES (NEXTVAL('ITP.S_DEVICE'), '00-A3-D3-FF-C0-6E', CURRENT_TIMESTAMP(), 49.456409, 11.078682);