

-- Tabelle: T_DEVICE
-- Enthält alle registrierten Geräte mit Koordinaten.
CREATE TABLE ITP.T_DEVICE
( 
	PK_DEVICEID INT PRIMARY KEY NOT NULL, 
	IDENTIFIER VARCHAR(12) NOT NULL, 
	ACTIVITY DATETIME NOT NULL, 
	LATITUDE DOUBLE NOT NULL, 
	LONGITUDE DOUBLE NOT NULL 
);
ALTER TABLE ITP.T_DEVICE ADD CONSTRAINT IDENTIFIER_UNIQUE UNIQUE(IDENTIFIER);
CREATE SEQUENCE ITP.S_DEVICE;

INSERT INTO ITP.T_DEVICE (PK_DEVICEID, IDENTIFIER, ACTIVITY, LATITUDE, LONGITUDE) VALUES (NEXTVAL('ITP.S_DEVICE'), '00B0D086BBF7', CURRENT_TIMESTAMP(), 49.456409, 11.078682);
INSERT INTO ITP.T_DEVICE (PK_DEVICEID, IDENTIFIER, ACTIVITY, LATITUDE, LONGITUDE) VALUES (NEXTVAL('ITP.S_DEVICE'), '00A3D3FFC06E', CURRENT_TIMESTAMP(), 49.456409, 11.078682);