

-- Tabelle: T_DEVICE
-- Enthält alle registrierten Geräte mit Koordinaten.
CREATE TABLE ITP.T_DEVICE
( 
	PK_DEVICEID INT PRIMARY KEY NOT NULL, 
	IDENTIFIER VARCHAR(255) NOT NULL, 
	ACTIVITY DATETIME NOT NULL, 
	LATITUDE DOUBLE NOT NULL, 
	LONGITUDE DOUBLE NOT NULL,
	NOTIFICATION DATETIME NULL, 
);
ALTER TABLE ITP.T_DEVICE ADD CONSTRAINT IDENTIFIER_UNIQUE UNIQUE(IDENTIFIER);
CREATE SEQUENCE ITP.S_DEVICE;

INSERT INTO ITP.T_DEVICE (PK_DEVICEID, IDENTIFIER, ACTIVITY, LATITUDE, LONGITUDE) VALUES (NEXTVAL('ITP.S_DEVICE'), '00b0d086bbf7', CURRENT_TIMESTAMP(), 49.456409, 11.078682);
INSERT INTO ITP.T_DEVICE (PK_DEVICEID, IDENTIFIER, ACTIVITY, LATITUDE, LONGITUDE) VALUES (NEXTVAL('ITP.S_DEVICE'), '00a3d3ffc06e', CURRENT_TIMESTAMP(), 49.456409, 11.078682);



CREATE TABLE ITP.T_NOTIFICATION
( 
	PK_NOTIFICATIONID INT PRIMARY KEY NOT NULL, 
	FK_DEVICEID INT NOT NULL, 
	ACTIVITY DATETIME NOT NULL, 
	LATITUDE DOUBLE NOT NULL, 
	LONGITUDE DOUBLE NOT NULL,
    LEVEL INT NOT NULL 
);

ALTER TABLE ITP.T_NOTIFICATION ADD FOREIGN KEY(FK_DEVICEID) REFERENCES ITP.T_DEVICE(PK_DEVICEID);

ALTER TABLE  ITP.T_NOTIFICATION 
ADD CONSTRAINT LEVELCHECKMIN
CHECK  (level > 0)

ALTER TABLE  ITP.T_NOTIFICATION 
ADD CONSTRAINT LEVELCHECKMAX
CHECK  (level < 4)

INSERT INTO ITP.T_NOTIFICATION (PK_NOTIFICATIONID, FK_DEVICEID, ACTIVITY, LATITUDE, LONGITUDE, LEVEL) VALUES (NEXTVAL('ITP.S_NOTIFICATION'), 136, CURRENT_TIMESTAMP(), 49.456411, 11.078605, 1);
CREATE SEQUENCE ITP.S_NOTIFICATION;

CREATE TABLE ITP.T_EARTHQUAKE
( 
	PK_EARTHQAUKEID INT PRIMARY KEY NOT NULL, 
	LATITUDE DOUBLE NOT NULL, 
	LONGITUDE DOUBLE NOT NULL, 
	ACTIVITY DATETIME NOT NULL,
	RADIUS DOUBLE NOT NULL,
	DEVICES INT NOT NULL,
	RATIO DOUBLE NOT NULL
);

CREATE SEQUENCE ITP.S_EARTHQUAKE;

INSERT INTO ITP.T_EARTHQUAKE (PK_EARTHQAUKEID, LATITUDE, LONGITUDE, ACTIVITY, RADIUS, DEVICES, RATIO) VALUES (NEXTVAL('ITP.S_EARTHQUAKE'), 136, CURRENT_TIMESTAMP(), 49.456411, 11.078605, 1);










